oracle:
    host : sys/sys123@192.168.0.131:1521/RAC
    hostIP : 192.168.0.131
    user : sys
    password : sys123
    sql : >
       select df.tablespace_name  as tableSpaceName, df.totalspace as totalMB, totalusedspace as usedMB, (df.totalspace - tu.totalusedspace) as freeMB, round(100 * ( (df.totalspace - (df.totalspace - tu.totalusedspace)) /df.totalspace)) as pctUsedSpace,
       round(100 * ( (df.totalspace - tu.totalusedspace)/ df.totalspace)) as pctFreeSpace from (select tablespace_name, round(sum(bytes) / 1048576)  totalSpace from dba_data_files group by tablespace_name) df,
       (select round(sum(bytes)/(1024*1024)) totalusedspace, tablespace_name from dba_segments group by tablespace_name) tu where df.tablespace_name = tu.tablespace_name